### ISSUE TITLE
city.csvがドメイン名だけじゃないやつがいる

### ISSUE THREAD

**Issue by yuiseki** [yuiseki/vscovid-crawler#22]

**Comment by takano32** [comment]
「city.csvがドメイン名だけじゃないやつがいる」というタイトルがよく分からなかった。

「city.csvにドメイン名のみではなくパスもふくんだ URL がある」ってことかな？

**Comment by yuiseki** [comment]
はい、なおしました

**Comment by yuiseki** [comment]
https?://domain
という形式で統一したかった
