### ISSUE TITLE
grepをxargs使って並列処理にしたい

### ISSUE THREAD

**Issue by yuiseki** [yuiseki/vscovid-crawler#4]
https://hacknote.jp/archives/28518/

これを参考にすればできるはず

**Comment by takano32** [comment]
(たぶん、)秒でできるのでアサインほしい。

**Comment by takano32** [comment]
うーんと。 xargs のケースは複数のファイルを指定している方法。
`-r` だと違う方法の方がよさそう。

https://takuya-1st.hatenablog.jp/entry/2014/06/29/120820
