### ISSUE TITLE
テストフレームワークを導入してユニットテストする

### ISSUE THREAD

**Issue by yuiseki** [yuiseki/vscovid-crawler#42]
候補
- https://github.com/sstephenson/bats
- https://shellspec.info/

**Comment by 515hikaru** [comment]
`make test` はこのテストを走らせるジョブにする形ですかね。

**Comment by yuiseki** [comment]
そうしたいです

**Comment by yuiseki** [comment]
テストフレームワークは役に立たなかったのでシェルスクリプトでテストを書いた
